highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://fmirus.github.io/vitae
author: Florian Mirus

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Florian Mirus's Resume
name: Florian Mirus
email: florian.mirus@gmx.net
email_full: mailto:florian.mirus@gmx.net
website: fmirus.github.io
website_full: https://fmirus.github.io
github: fmirus
#twitter: twitter
bitbucket: fmirus # username
linkedin: florian-mirus-137440b8
xing: Florian_Mirus2
# tel: +49 151 23 42 22 41
# tel_full: tel:+4915123422241
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
google_maps: 'https://www.google.de/maps/place/M%C3%BCnchen/@48.1545703,11.2616557,10z/data=!3m1!4b1!4m5!3m4!1s0x479e75f9a38c5fd9:0x10cb84a7db1987d!8m2!3d48.1351253!4d11.5819806'
# address: Hauptstrasse 8F
# postcode: 85386
city: Munich
country: Germany
google_analytics: UA-99083854-2

# needed for travis-ci build
exclude: [vendor]
